### ISSUE TITLE
Behat didn't work with scenario which need to be login

### ISSUE THREAD

**Issue by tamnv** [leymannx/drupal-circleci-behat#5]
We write a test case which need to login, but it can't login. I think the reason can come from session, it doesn't store session login

**Comment by normanlolx** [comment]
Hey thanks for the issue. But I need more info. Test code. And error output. For example. Please provide as much info as you can.

**Comment by tamnv** [comment]
Thanks for replying, this is more information
Test code:
```
Scenario Outline: User creation with different roles using admin role
    Given I am on "/user"
    When I fill in the following:
      | edit-name | [admin] |
      | edit-pass | [admin] |
    And I press the "edit-submit" button
    When I am on "/admin/people/create"
    Then I fill in the following:
      | edit-name | <username> |
      | edit-mail | <usermail> |
      | edit-pass-pass1 | <password1> |
      | edit-pass-pass2 | <password2> |
      | edit-field-user-first-name-und-0-value | <first_name> |
      | edit-field-user-last-name-und-0-value  | <last_name>  |
      | edit-field-nickname-und-0-value        | <nickname> |
    And I check "<role>"
    And the "<role>" checkbox should be checked
    And I press the "edit-submit" button

  Examples:
    | username | usermail | password1 | password2 | first_name | last_name | nickname | role |
    | student981 | student981@mailinator.com | student@981 | student@981 | Michael | Smith | Michael S | Student |
```

Error output:
`Form field with id|name|label|value "edit-mail" not found. (Behat\Mink\Exception\ElementNotFoundException)`

**Comment by normanlolx** [comment]
Hey, so the setup is working. You just need to fix your specific test. Behat doesn't recognize your email field. Maybe you need to log in with a different role first. Maybe the field is named differently in your setup. Maybe you should let Behat make screenshots on errors. Nonetheless this goes a little bit beyond the scope of this sample repo.

**Comment by staminna** [comment]
I also have the exact error as tamnv.
@tamnv Did you manage to find out the issue?

**Comment by normanlolx** [comment]
Hey hey, can you please dump your current `behat.yml` and your scenario? Are you maybe running tests against a non-English site?

**Comment by normanlolx** [comment]
Apart from the login in with a certain role can easily be achieved with `@api` tagged scenarios. But I guess the sample doesn't incorporate that, yet. Will update repo soon.

**Comment by staminna** [comment]
Sure, but I am not using your whole project, but since I found the same issue as Tamnv, I thought one of you could help.

behat.yml

![image](https://user-images.githubusercontent.com/515180/51997778-b113f100-24b7-11e9-93e3-6f0d64c6a118.png)


scenary.feature:

`Feature: Join Group
  In order to join
  User should be able to login
  open example
  Submit form sucessfully.

  @api
    Scenario: Login and join.
    Given I am on "/user"
    When I fill in the following:
        | edit-name | bddtest |
        | pass | Behattest101 |
    And press "Login"
    When I am at "/en"
    When I click "Join"
    Then I should see the heading "Thank you for joining..."
`

**Comment by normanlolx** [comment]
Maybe you can have a look at the [`login.feature`](https://github.com/leymannx/drupal-circleci-behat/blob/develop/tests/behat/features/login.feature) which works just fine.

**Comment by normanlolx** [comment]
Code highlighting on Github: https://help.github.com/articles/creating-and-highlighting-code-blocks/

Screenshots of code really are a pain to read. Especially on mobile devices.

**Comment by normanlolx** [comment]
Shouldn't the `api_driver` be `drupal`? See the [`behat.yml`](https://github.com/leymannx/drupal-circleci-behat/blob/develop/tests/behat/behat.yml) which works just fine.

**Comment by staminna** [comment]
I set `api_driver `to `drupal` and checked your behat.yml file, but now the issue is 

>  Scenario: Login in as authenticated user                            # features\login.feature:11
    Given I am logged in as a user with the "Authenticated user" role # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      Could not open connection: Payload received from webdriver is not valid json: <HTML><HEAD>
</BODY></HTML> (Behat\Mink\Exception\DriverException)

**Comment by normanlolx** [comment]
Any chance you are using `blt`? Is this scenario tagged `@api`? Any other tags? I don't see that in your quote. What does `chromedriver --version` return? What does `selenium-server --version` return?

**Comment by staminna** [comment]
Thank you for helping me out on this. 
The scenario is tagged with `@api`

chromedriver: `2.45.61`xxxx
 java -jar `selenium-server-standalone-2.44.0.jar` -role hub
Picked up _JAVA_OPTIONS: -Duser.home=C:\USERS\domijor
09:40:54.099 INFO - Launching a selenium grid server

**Comment by normanlolx** [comment]
The Selenium version you are using is pretty old (it's from 2014). Any chance you could update it to v3 and retry?

**Comment by normanlolx** [comment]
Although it's not very likely that upgrading Selenium will fix the issue, as you don't seem to make any use of it, nor is the scenario tagged with `@javascript`. It must be something different. Anyways quite outdated the Selenium.

**Comment by normanlolx** [comment]
Where's the original `behat.yml` coming from? What's that `You can use profiles if you wish to allow users to run tests locally` note? I never use anything special when running tests locally. Just the default `behat.yml` linked above.

**Comment by staminna** [comment]
It's from [https://behat-drupal-extension.readthedocs.io/en/3.1/environment.html]( https://behat-drupal-extension.readthedocs.io/en/3.1/environment.html
)
`λ behat
Feature: Login testing.

  @api @javascript
  Scenario: Log in as Existing user      # features\login.feature:3
    Given I am an anonymous user         # Drupal\DrupalExtension\Context\DrupalContext::assertAnonymousUser()
      Could not open connection: Webdriver http error: 404, payload :<HTML><HEAD>`

**Comment by staminna** [comment]
The issue seems to be happening because of a "[webdriver](https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/AbstractWebDriver.php#L145-L150)", 
but it might as well be caused by MinkExtension
